package com.example.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table APP_RUN_CONFIG.
 */
public class AppRunConfig {

    private Long id;
    private String week;
    private String time;
    private String name;
    private String appIcon;
    private String packName;
    private String type;

    public AppRunConfig() {
    }

    public AppRunConfig(Long id) {
        this.id = id;
    }

    public AppRunConfig(Long id, String week, String time, String name, String appIcon, String packName, String type) {
        this.id = id;
        this.week = week;
        this.time = time;
        this.name = name;
        this.appIcon = appIcon;
        this.packName = packName;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWeek() {
        return week;
    }

    public void setWeek(String week) {
        this.week = week;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAppIcon() {
        return appIcon;
    }

    public void setAppIcon(String appIcon) {
        this.appIcon = appIcon;
    }

    public String getPackName() {
        return packName;
    }

    public void setPackName(String packName) {
        this.packName = packName;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
