package com.example.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table APP_RUN_RECORD.
 */
public class AppRunRecord {

    private Long id;
    private java.util.Date startTime;
    private java.util.Date exitTime;
    private String appInstance;
    private String appInstanceId;
    private String runTime;
    private Integer allRunNumber;
    private Long allRunDuration;
    private String appInstancePackageName;

    public AppRunRecord() {
    }

    public AppRunRecord(Long id) {
        this.id = id;
    }

    public AppRunRecord(Long id, java.util.Date startTime, java.util.Date exitTime, String appInstance, String appInstanceId, String runTime, Integer allRunNumber, Long allRunDuration, String appInstancePackageName) {
        this.id = id;
        this.startTime = startTime;
        this.exitTime = exitTime;
        this.appInstance = appInstance;
        this.appInstanceId = appInstanceId;
        this.runTime = runTime;
        this.allRunNumber = allRunNumber;
        this.allRunDuration = allRunDuration;
        this.appInstancePackageName = appInstancePackageName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getStartTime() {
        return startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public java.util.Date getExitTime() {
        return exitTime;
    }

    public void setExitTime(java.util.Date exitTime) {
        this.exitTime = exitTime;
    }

    public String getAppInstance() {
        return appInstance;
    }

    public void setAppInstance(String appInstance) {
        this.appInstance = appInstance;
    }

    public String getAppInstanceId() {
        return appInstanceId;
    }

    public void setAppInstanceId(String appInstanceId) {
        this.appInstanceId = appInstanceId;
    }

    public String getRunTime() {
        return runTime;
    }

    public void setRunTime(String runTime) {
        this.runTime = runTime;
    }

    public Integer getAllRunNumber() {
        return allRunNumber;
    }

    public void setAllRunNumber(Integer allRunNumber) {
        this.allRunNumber = allRunNumber;
    }

    public Long getAllRunDuration() {
        return allRunDuration;
    }

    public void setAllRunDuration(Long allRunDuration) {
        this.allRunDuration = allRunDuration;
    }

    public String getAppInstancePackageName() {
        return appInstancePackageName;
    }

    public void setAppInstancePackageName(String appInstancePackageName) {
        this.appInstancePackageName = appInstancePackageName;
    }

}
