package com.example.greenDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appInstanceDaoConfig;
    private final DaoConfig appRunRecordDaoConfig;
    private final DaoConfig appRunConfigDaoConfig;
    private final DaoConfig appPackageDaoConfig;
    private final DaoConfig appRunConfigDetailDaoConfig;
    private final DaoConfig timeDaoConfig;

    private final AppInstanceDao appInstanceDao;
    private final AppRunRecordDao appRunRecordDao;
    private final AppRunConfigDao appRunConfigDao;
    private final AppPackageDao appPackageDao;
    private final AppRunConfigDetailDao appRunConfigDetailDao;
    private final TimeDao timeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appInstanceDaoConfig = daoConfigMap.get(AppInstanceDao.class).clone();
        appInstanceDaoConfig.initIdentityScope(type);

        appRunRecordDaoConfig = daoConfigMap.get(AppRunRecordDao.class).clone();
        appRunRecordDaoConfig.initIdentityScope(type);

        appRunConfigDaoConfig = daoConfigMap.get(AppRunConfigDao.class).clone();
        appRunConfigDaoConfig.initIdentityScope(type);

        appPackageDaoConfig = daoConfigMap.get(AppPackageDao.class).clone();
        appPackageDaoConfig.initIdentityScope(type);

        appRunConfigDetailDaoConfig = daoConfigMap.get(AppRunConfigDetailDao.class).clone();
        appRunConfigDetailDaoConfig.initIdentityScope(type);

        timeDaoConfig = daoConfigMap.get(TimeDao.class).clone();
        timeDaoConfig.initIdentityScope(type);

        appInstanceDao = new AppInstanceDao(appInstanceDaoConfig, this);
        appRunRecordDao = new AppRunRecordDao(appRunRecordDaoConfig, this);
        appRunConfigDao = new AppRunConfigDao(appRunConfigDaoConfig, this);
        appPackageDao = new AppPackageDao(appPackageDaoConfig, this);
        appRunConfigDetailDao = new AppRunConfigDetailDao(appRunConfigDetailDaoConfig, this);
        timeDao = new TimeDao(timeDaoConfig, this);

        registerDao(AppInstance.class, appInstanceDao);
        registerDao(AppRunRecord.class, appRunRecordDao);
        registerDao(AppRunConfig.class, appRunConfigDao);
        registerDao(AppPackage.class, appPackageDao);
        registerDao(AppRunConfigDetail.class, appRunConfigDetailDao);
        registerDao(Time.class, timeDao);
    }
    
    public void clear() {
        appInstanceDaoConfig.getIdentityScope().clear();
        appRunRecordDaoConfig.getIdentityScope().clear();
        appRunConfigDaoConfig.getIdentityScope().clear();
        appPackageDaoConfig.getIdentityScope().clear();
        appRunConfigDetailDaoConfig.getIdentityScope().clear();
        timeDaoConfig.getIdentityScope().clear();
    }

    public AppInstanceDao getAppInstanceDao() {
        return appInstanceDao;
    }

    public AppRunRecordDao getAppRunRecordDao() {
        return appRunRecordDao;
    }

    public AppRunConfigDao getAppRunConfigDao() {
        return appRunConfigDao;
    }

    public AppPackageDao getAppPackageDao() {
        return appPackageDao;
    }

    public AppRunConfigDetailDao getAppRunConfigDetailDao() {
        return appRunConfigDetailDao;
    }

    public TimeDao getTimeDao() {
        return timeDao;
    }

}
